### PR TITLE
Update 2023-05-08-is-cyclomatic-complexity-really-related-to-branch-c…

### PR DESCRIPTION
**Pull request by m4rsh**
…overage.html

Fix typo and insert missing delimiters.

### CODE REVIEW

**Comment by m4rsh** [comment]
As I am from Germany, it seems, I made the mistake, not to differentiate between restrictive clauses and non-restrictive clauses in the English language. Therefore, please ignore my comma corrections.

**Comment by ploeh** [comment]
That makes us two non-English-speaking natives 😉

No worries, commas are hard

**Comment by m4rsh** [comment]
Thank you for your kind words. It's not easy, but learning from mistakes is the best way to getting better. ;)

**Comment by m4rsh** [comment]
Thanks for your kind words. Making mistakes is the best way getting better.😀

**Pull request merged**
