### PR TITLE
added link to Data.Monoid.Endo

### PR DESCRIPTION
**Pull request by TysonMN**
That `Endo` is `Data.Monoid.Endo`, right?  Is this a good link to put there?

### CODE REVIEW

**Comment by ploeh** [comment]
`Endo` is in [Data.Semigroup](https://hackage.haskell.org/package/base/docs/Data-Semigroup.html) in [base](https://hackage.haskell.org/package/base).

When I write Haskell articles, I typically don't link to the types in _base_ or some of the other 'base libraries' such as _time_, _containers_, or _mtl_... I could, but the prose in such an article tends to mention so many of these that I'd have to add a lot of links, and I'm honestly too lazy to add so many.

I'm assuming that the value in doing so is limited, since I think that the majority of the few people who read the Haskell articles know where to find them anyway...

Since you're asking, that assumption might be wrong...

**Comment by ploeh** [comment]
Oh, and if you want to add the link, I always try to link to a version-neutral version of the page, like I've done above...

**Comment by TysonMN** [comment]
I have programed in Haskell just a few times, so many elementary Haskell things are still new to me.  I was curious about specific type class because it is so integral to your prototype.

And thanks for pointing out that I had included version in that URL.  I also prefer to exclude that.

I just force pushed an update.  How is that?

**Comment by ploeh** [comment]
I think that it'd be more appropriate to link to [the definition of Endo](https://hackage.haskell.org/package/base/docs/Data-Semigroup.html#t:Endo).

**Comment by TysonMN** [comment]
The anchor tag in the URL in this PR takes the browser to the line ` Semigroup (Endo a)`, both `Semigorup` and `Endo` have hyperlinks, and the link for `Endo` is the same as the one you have suggested.

**Comment by TysonMN** [comment]
I think you are right though.  `Endo a -> a` is actually a monoid, so the fact that it is a semigroup is immediate.  I will make that change.

**Comment by TysonMN** [comment]
Just force pushed that change.

**Pull request merged**
