### PR TITLE
corrected second for first typo

### PR DESCRIPTION
**Pull request by bender2k14**

### CODE REVIEW

**Comment by ploeh** [comment]
Thank you, but I'm _fairly_ sure that the sentence as written correctly describes what's going on..(?) 😄

**Comment by ploeh** [comment]
Correct me if I'm wrong, though 😄

**Comment by bender2k14** [comment]
Oh, yes.  You are correct.  Sorry for my mistake.

**Comment by ploeh** [comment]
FWIW, once you brought this to my attention, I had to read the sentence a couple of times before I came to that conclusion. I could probably have phrased it better...

**Comment by bender2k14** [comment]
I know this operation as the tensor product of a two-dimensional column vector with a three-dimensional row vector
https://en.wikipedia.org/wiki/Tensor_product

**Comment by ploeh** [comment]
Uh, oh, it's been 25+ years since I had to think about vectors... 😓

**Pull request closed without merging**
