### PR TITLE
Create ActionFilter with unit of work dependency injection

### PR DESCRIPTION
**Pull request by tangokhi**

### CODE REVIEW

**Comment by ploeh** [comment]
Thank you for writing.

If you wish to comment on a particular article, please submit a pull request for a change to that document. Make sure it's appropriately formatted.

More guidelines are here: https://github.com/ploeh/ploeh.github.com#comments

**Comment by tangokhi** [comment]
Hi 
I have posted the question on stackoverflow. 

http://stackoverflow.com/questions/34177827/custom-action-filter-unity-dependency-injection-web-api-2

Could you please provide your suggestion.

Thank you

**Comment by ploeh** [comment]
:+1: I've left a comment there.

**Comment by tangokhi** [comment]
Thank you for your comment. I made a typing mistake which I have corrected now. 

Thanks

**Pull request closed without merging**
