### PR TITLE
Comment on colour-mixing magmas

### PR DESCRIPTION
**Pull request by mark-wiemer**

### CODE REVIEW

**Comment by ploeh** [comment]
Thank you for writing. I think that your previous typo correction introduced a merge conflict in this pull request. As per normal GitHub protocol, would you be so kind to resolve the conflict?

**Comment by ploeh** [comment]
Sorry about the inconvenience

**Comment by mark-wiemer** [comment]
Hey @ploeh, I resolved the merge conflicts :)

**Comment by ploeh** [comment]
Thank you for writing. I've left [a brief response on the page](https://blog.ploeh.dk/2018/01/02/colour-mixing-magma/#11459c2a1d10452aaa0e4fcc82934360).

**Pull request merged**
