### PR TITLE
New comment on post from March 18

### PR DESCRIPTION
**Pull request by VTJDailey**
Hopefully I've structured this pull request correctly -- I don't do a lot of this on GitHub!

Thanks so much for the work you do!

### CODE REVIEW

**Comment by ploeh** [comment]
Thank you for your comment. It deserves a comprehensive answer, but since I'm currently travelling, it may take a while before I find the time to answer.

**Comment by VTJDailey** [comment]
Not a problem.  I'm grateful for any help sorting this out in my mind.  In the meantime I've got a lot of reading to do.

If I have further updates or clarifications to bring to my post, how do you prefer them to appear on your website?  Should I send a pull request for a new followup comment, or update the existing one in place?

**Comment by ploeh** [comment]
If you have more to add, you'll need to send a new pull request, as this particular pull request is already closed (because it was accepted).

**Comment by ploeh** [comment]
I've now left a response on the page: http://blog.ploeh.dk/2016/03/18/functional-architecture-is-ports-and-adapters

**Comment by VTJDailey** [comment]
Thanks a lot!  It will probably take me some time to digest things and come up with a coherent response.

**Pull request merged**
