### PR TITLE
Added Comment asking Mark a Question

### PR DESCRIPTION
**Pull request by benbedinghaus**
Added question on how Mark would go about designing a repository layer.

### CODE REVIEW

**Comment by benbedinghaus** [comment]
Mark,

Would your booking code be an example of how you would design a repository layer of some type? I that you’re persisting info to files but where its stored is of no consequence.

https://github.com/ploeh/Booking

Thanks,

Ben Bedinghaus
The David J. Joseph Company
Software Engineer
ben.bedinghaus@djj.com

**Comment by ploeh** [comment]
> Would your booking code be an example of how you would design a repository layer of some type?

Not today, no, but I could probably work with something like it. That code base is six years old, and I think that most people's styles evolve over time. At a glance, and what I remember of it, it's not half bad, but I wouldn't do it like that today. Specifically, I wouldn't have an `ICapacityRepository` interface. I'd most like just have a function to read from the data store, and one to write to it.

**Comment by benbedinghaus** [comment]
I think you also used an IStoreWriter and IStoreReader for writing files and that feels a lot more like what you are describing replacing the ICapacityRepository with.?

Thanks,

Ben Bedinghaus
The David J. Joseph Company
Software Engineer
ben.bedinghaus@djj.com

**Comment by ploeh** [comment]
Yes, that sounds right.

**Comment by benbedinghaus** [comment]
Thank you for taking your time to answer my questions. I’m always looking to get better. I really like your pluralsight course on SOLID. I’m trying to learn a lot more about those and move my company in that direction.

Thanks,

Ben Bedinghaus
The David J. Joseph Company
Software Engineer
ben.bedinghaus@djj.com

**Pull request merged**
