### PR TITLE
Add comment

### PR DESCRIPTION
**Pull request by cmeeren**
Hope everything's formatted correctly!

### CODE REVIEW

**Comment by cmeeren** [comment]
Oh, I see I re-used the GUID from my previous comment to another post (copy-paste). Let me know if you want me to fix it.

**Comment by ploeh** [comment]
I can fix that, but I suppose that you also want the name updated?

**Comment by cmeeren** [comment]
Oh, sorry, I thought I copied my own comment. Things went too quick there. Yes, please!

```html
<div class="comment-author"><a href="https://www.relativisticramblings.com/">Christer van der Meeren</a></div>
````

**Comment by ploeh** [comment]
Thank you for writing 👍 I've added [a brief response to the page](https://blog.ploeh.dk/2019/12/02/refactoring-registration-flow-to-functional-architecture/#e90332adb7d24e2b8aa1484c302b6f8c), but as you can tell, I'll provide a more thorough answer next week (I hope).

**Comment by cmeeren** [comment]
Thanks!

For clarity:

> When I do that, however, I don't plan to reproduce your updated example, or address it in detail. I see nothing in it that invalidates what I've already written.

I agree. Nor was that my intention. While my comment used the more complex version, I see the summary/evaluation as being relevant for your original refactoring, too.

**Comment by ploeh** [comment]
FWIW, I've now added [a more comprehensive response to the page](https://blog.ploeh.dk/2019/12/02/refactoring-registration-flow-to-functional-architecture/#fea1498fe43543f29a01eb6101dbdb9f).

**Pull request merged**
