### PR TITLE
Comment on async injection.

### PR DESCRIPTION
**Pull request by votroto**
What a curious way to write comments.

Feels quite uneasy. Hopefully I've understood your intent. Sorry, I couldn't really figure out how to generate a comment id.

### CODE REVIEW

**Comment by TysonMN** [comment]
I generate mine [here](https://www.guidgenerator.com/).

**Comment by votroto** [comment]
That's a first... :D. Thanks. 

Does it have to be generated by with the use of a CPRNG, or can I just mash the keyboard until it looks sufficiently random? Can I just copy someone else's? Should I check for uniqueness? Is anyone else going to?

The little README doesn't say. :D

**Comment by TysonMN** [comment]
It is just a [URI fragment](https://en.wikipedia.org/wiki/URI_fragment).  It suffices if it is unique on the page.  You can mash the keyboard if you want.  Then it is easy to check for uniqueness in the page with the "find"  feature of your preferred text editor.

**Comment by ploeh** [comment]
It's fine; I check it before I merge the PR 😄

**Comment by ploeh** [comment]
I'll post a little note here when I've published an answer, but it may be some days...

**Comment by ploeh** [comment]
Thank you for writing. I've left [a response on the page](https://blog.ploeh.dk/2019/02/11/asynchronous-injection/#cb014e7f4c6d420faab1f3328331e7ba).

**Pull request merged**
