### PR TITLE
Comment about builder pattern

### PR DESCRIPTION
**Pull request by bender2k14**

### CODE REVIEW

**Comment by ploeh** [comment]
Tyson, thank you for writing. This comment could spark an interesting new branch of research, but even for a short, tentative answer, I'd need to consult my copy of the GoF book, and I'm currently travelling.

I'll post an answer as soon as possible, but it'll take days until I'm back home again.

**Comment by bender2k14** [comment]
Hello Mark.  It was my pleasure.  I am glad that my comment has had this effect on you :)

Please take your time.  I am in no hurry.  Enjoy your travels :)

**Comment by ploeh** [comment]
FWIW, I've added [a preliminary answer to the page](https://blog.ploeh.dk/2017/09/11/test-data-without-builders/#ba26e928d57d4b649942deb1e1ae18f1).

**Comment by ploeh** [comment]
I've now added [another response to the page](https://blog.ploeh.dk/2017/09/11/test-data-without-builders/#042e8f7aeba042659d9cf626f78f8636).

**Pull request merged**
