### PR TITLE
Limiting Atom and RSS feeds to 10 posts

### PR DESCRIPTION
**Pull request by xdaDaveShaw**
As discussed on twitter and mentioned via my [blog](http://taeguk.co.uk/blog/dealing-with-newsblur-and-large-feeds/), NewsBlur has problems with large RSS / Atom feeds. Jekyll supports limiting the number of posts in the feed. I've picked 10 as an arbitrary number.

### CODE REVIEW

**Comment by ploeh** [comment]
Thank you for your contribution. As explained in #76, Atom feeds should be paged. As described in #77, it would also be nice if the RSS feed is, but I'm not sure if that's doable.

Assuming that it isn't possible paging RSS feeds, we can move forward with the RSS change, but please either revert the change to the Atom feed (by far the easiest solution), or implement paging.

**Comment by xdaDaveShaw** [comment]
Doh! I never thought to look into if you have anything logged for this - I've only just discovered Jekyll and found this setting via Nick Craver's blog. I've reverted the Atom changes, no idea how I would do that with Jekyll or Liquid. Looking at the [RSS Spec](https://validator.w3.org/feed/docs/rss2.html) there's nothing supporting paging.

**Comment by ploeh** [comment]
Thank you! It's now live on the blog. Hope it helps :smile:

**Comment by xdaDaveShaw** [comment]
NewsBlur seems to have picked it up. I'll run my Yahoo Pipes along side the RSS until your next blog post to see if it works.

Thanks

**Pull request merged**
