### PR TITLE
Adds a comment to the 'Monoids, semigroups and friends' post

### PR DESCRIPTION
**Pull request by ecampidoglio**
I left a comment in the article titled ["_Monoids, semigroups and friends_"](http://blog.ploeh.dk/2017/10/05/monoids-semigroups-and-friends/).

### CODE REVIEW

**Comment by ploeh** [comment]
Hi Enrico, thanks for writing. I'd like to respond, but I'm afraid that it will have to wait until the weekend.

**Comment by ecampidoglio** [comment]
Sure, no problem. Thank you for sharing your insights!

_P.S. Sorry about the time zone._ 😊

**Comment by ploeh** [comment]
> P.S. Sorry about the time zone.

No worries. You provided a perfectly valid date and time string. For various reasons (that I really don't feel like typing out right now), years ago, I decided to stick to UTC times on my blog. It's hardly perfect...

**Comment by ploeh** [comment]
Once again, thank you for writing. I've now left a short response on the page: http://blog.ploeh.dk/2017/10/05/monoids-semigroups-and-friends

**Pull request merged**
