### PR TITLE
Update 2013-05-01-rest-lesson-learned-avoid-hackable-urls.html

### PR DESCRIPTION
**Pull request by naasking**
added comment about Clavis

### CODE REVIEW

**Comment by ploeh** [comment]
Thank you for writing; you'll have to change the `author` tag before I will pull.

**Comment by naasking** [comment]
Oops, fixed!

**Comment by ploeh** [comment]
The *link* as well :smile: 

If you don't want your name to link to anything, you're welcome to just remove the surrounding `a` tag - other people have done that as well.

**Comment by naasking** [comment]
Sorry, that'll learn me to write and try setting up a cross compile environment simultaneously...

**Comment by ploeh** [comment]
Well, I *do* realize that this commenting system is a bit inconvenient for the casual commenter, but it provides a lot of other great benefits, and ultimately I believe that the advantages are greater than the disadvantages.

**Pull request merged**
