### PR TITLE
Added comment

### PR DESCRIPTION
**Pull request by pito-svk**

### CODE REVIEW

**Comment by ploeh** [comment]
Thank you for writing. I don't think I can help you, since I don't really program in Clojure...

I'd like to publish your question, since perhaps others would be able to help you, but when I follow the command-line instructions, I can't get it to work:

```
mark@ploeh MINGW64 ~/Documents/ploeh/Blog (master)
$ git checkout -b pito-svk-patch-3 master
Switched to a new branch 'pito-svk-patch-3'

mark@ploeh MINGW64 ~/Documents/ploeh/Blog (pito-svk-patch-3)
$ curl -L https://github.com/ploeh/ploeh.github.com/pull/275.patch | git am -3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   148    0   148    0     0    175      0 --:--:-- --:--:-- --:--:--   175
100    32    0    32    0     0     22      0 --:--:--  0:00:01 --:--:--    73
Patch is empty. Was it split wrong?
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
```

**Comment by pito-svk** [comment]
What about solution in javascript? Thanks.

**Comment by ploeh** [comment]
Sorry, I don't do JavaScript either... F# or Haskell 😃

**Comment by pito-svk** [comment]
Haskell is good. :) Would you mind? Thanks.

**Comment by ploeh** [comment]
While I _could_ translate the article's code to Haskell, I'm not sure it'd make much sense. It probably wouldn't be idiomatic Haskell code anyway...

**Pull request closed without merging**
