### PR TITLE
Comment on 2020-01-20-algebraic-data-types-arent-numbers-on-steroids.…

### PR DESCRIPTION
**Pull request by drewjcooper**
…html

Add a comment

### CODE REVIEW

**Comment by ploeh** [comment]
Thank you for writing 👍 I'd considered replying to Jakub's comment, but yours amply does that.

Did you mean to respond to Jakub, or is the question directed at me?

**Comment by ploeh** [comment]
Well, regardless of who you directed your question at, you got [a reply from Jakub](https://blog.ploeh.dk/2020/01/20/algebraic-data-types-arent-numbers-on-steroids/#bd48b3267e014ccc9b377e983369ddca) 😄

**Comment by drewjcooper** [comment]
Mark, I was intending the question for yourself. I'm not sure that the code in the original post supports the point you're trying to make in the text, but it's entirely possible that i'm missing something.

The `Trade` data type doesn't inherently prevent you from adding values of different currencies, although to solve the given problem you necessarily have to separate the currency types. This seems to me, though, to be a feature of the data processing algorithm, rather than the data type. Again, am I missing something?

**Comment by ploeh** [comment]
Okay, I just wanted to be sure. FWIW I've now left [a response on the page](https://blog.ploeh.dk/2020/01/20/algebraic-data-types-arent-numbers-on-steroids/#c9069e6554934325a86a27921cff7ac3). Please write again if you don't find it satisfactory 😄

**Pull request merged**
