### PR TITLE
Comment added to 'Waiting to never happen' post

### PR DESCRIPTION
**Pull request by ladeak**
Comment added to 'Waiting to never happen' post

### CODE REVIEW

**Comment by ploeh** [comment]
I haven't forgotten this question - I'm just really busy ATM.

**Comment by ladeak** [comment]
Any chance you had some time to think about it?

**Comment by ploeh** [comment]
I haven't forgotten about this, but I'm really busy at the moment. I'll respond when I have some time for it.

**Comment by ploeh** [comment]
Thank you for writing. I've left [a response on the page](https://blog.ploeh.dk/2022/05/23/waiting-to-never-happen/#552d192249594844937724b2b2f86efe).

**Comment by ladeak** [comment]
Thank you for the detailed answer.

**Pull request merged**
